### ISSUE TITLE
Document Notifications stopped working.

### ISSUE THREAD

**Issue by Dr-Blank** [The-Commit-Company/raven#1770]
Recently updated to Raven: v2.6.0 (develop) and document notification stopped working.

Below is an error log which likely could be the issue

```
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/utils/background_jobs.py", line 225, in execute_job
    retval = method(**kwargs)
      site = '******'
      method = <function send_raven_notifications at 0x7eb33b4cb7e0>
      event = None
      job_name = 'raven.raven_integrations.doctype.raven_document_notification.raven_document_notification.send_raven_notifications'
      kwargs = {'doc': <ToDo: siqrkrshi2>, 'notifications_to_send': [{'name': 'Todo Test', 'send_alert_on': 'New Document', 'condition': ''}, {'name': 'Todo Created', 'send_alert_on': 'New Document', 'condition': ''}], 'link_doctype': 'ToDo', 'link_document': 'siqrkrshi2', 'after_commit': True}
      user = '********'
      is_async = True
      retry = 0
      retval = None
      method_name = 'raven.raven_integrations.doctype.raven_document_notification.raven_document_notification.send_raven_notifications'
      before_job_task = 'frappe.monitor.start'
builtins.TypeError: send_raven_notifications() got an unexpected keyword argument 'after_commit'
```

ERPNext: v15.66.1 (version-15)
Frappe Framework: v15.72.4 (version-15)

**Comment by Dr-Blank** [comment]
i think the bug was introduced in #1761 

[job enques](https://github.com/The-Commit-Company/raven/blob/0b4cb3c7fd8f2322d82678f914e157e5180cea6f/raven/raven_integrations/doctype/raven_document_notification/raven_document_notification.py#L232-L239) with param `after_commit` but function definition [send_raven_notifications](https://github.com/The-Commit-Company/raven/blob/0b4cb3c7fd8f2322d82678f914e157e5180cea6f/raven/raven_integrations/doctype/raven_document_notification/raven_document_notification.py#L265) does not have a `after_commit`

**Comment by Dr-Blank** [comment]
@nikkothari22 thank you
