### ISSUE TITLE
Error on mobile apps after update to 2.8.3

### ISSUE THREAD

**Issue by jpettan** [The-Commit-Company/Raven#2026]
Hi Team,

We updated Raven to 2.8.3 today. All users are reporting that their accounts are getting logged out frequently with following message in their mobile apps - both ios and android. Screenshot attached. Reporting this issue for resolution.

<img width="946" height="2048" alt="Image" src="https://github.com/user-attachments/assets/dbaafdf9-1adf-4018-9229-d158f1283e84" />

**Comment by nikkothari22** [comment]
Hey @jpettan what's the version of Frappe on this site?

**Comment by jpettan** [comment]
Frappe Framework: v15.99.0 (HEAD)

**Comment by nikkothari22** [comment]
Hmm, hard to reproduce this. How often is this happening? Is it happening once every hour or so?

**Comment by jpettan** [comment]
Should be every hour.

**Comment by jpettan** [comment]
I see an error log entry in frappe every hour. Sharing the error - in case it is related.

'User' object has no attribute 'user_image'

Traceback with variables (most recent call last):
  File "apps/frappe/frappe/app.py", line 120, in application
    response = frappe.api.handle(request)
      request = <Request 'https://www.stergycleantech.com/api/method/frappe.integrations.oauth2.get_token' [POST]>
      response = None
      rollback = True
      e = AttributeError("'User' object has no attribute 'user_image'")
  File "apps/frappe/frappe/api/__init__.py", line 52, in handle
    data = endpoint(**arguments)
      request = <Request 'https://www.stergycleantech.com/api/method/frappe.integrations.oauth2.get_token' [POST]>
      endpoint = <function handle_rpc_call at 0x7f25ddd04180>
      arguments = {'method': 'frappe.integrations.oauth2.get_token'}
  File "apps/frappe/frappe/api/v1.py", line 40, in handle_rpc_call
    return frappe.handler.handle()
      method = 'frappe.integrations.oauth2.get_token'
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
  File "apps/frappe/frappe/handler.py", line 53, in handle
    data = execute_cmd(cmd)
      cmd = 'frappe.integrations.oauth2.get_token'
      data = None
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
      cmd = 'frappe.integrations.oauth2.get_token'
      from_async = False
      server_script = None
      method = <function get_token at 0x7f255cc0da80>
  File "apps/frappe/frappe/__init__.py", line 1754, in call
    return fn(*args, **newargs)
      fn = <function get_token at 0x7f255cc0da80>
      args = ()
      kwargs = {'grant_type': 'refresh_token', 'client_id': 'cfqth0fcgm', 'refresh_token': 'QnIWrJDCPWSS9bevxSryDkizUVClej', 'cmd': 'frappe.integrations.oauth2.get_token'}
      newargs = {'grant_type': 'refresh_token', 'client_id': 'cfqth0fcgm', 'refresh_token': 'QnIWrJDCPWSS9bevxSryDkizUVClej', 'cmd': 'frappe.integrations.oauth2.get_token'}
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
      args = ()
      kwargs = {'grant_type': 'refresh_token', 'client_id': 'cfqth0fcgm', 'refresh_token': 'QnIWrJDCPWSS9bevxSryDkizUVClej', 'cmd': 'frappe.integrations.oauth2.get_token'}
      apply_condition = <function whitelist.<locals>.innerfn.<locals>.<lambda> at 0x7f255cc0d9e0>
      func = <function get_token at 0x7f255cc0d940>
  File "apps/frappe/frappe/integrations/oauth2.py", line 127, in get_token
    _headers, body, _status = get_oauth_server().create_token_response(
      args = ()
      kwargs = {'grant_type': 'refresh_token', 'client_id': 'cfqth0fcgm', 'refresh_token': 'QnIWrJDCPWSS9bevxSryDkizUVClej', 'cmd': 'frappe.integrations.oauth2.get_token'}
      r = <Request 'https://www.stergycleantech.com/api/method/frappe.integrations.oauth2.get_token' [POST]>
  File "env/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 112, in wrapper
    return f(endpoint, uri, *args, **kwargs)
      endpoint = <oauthlib.openid.connect.core.endpoints.pre_configured.Server object at 0x7f2557596150>
      uri = 'https://www.stergycleantech.com/api/method/frappe.integrations.oauth2.get_token'
      args = ('POST', ImmutableMultiDict([('grant_type', 'refresh_token'), ('client_id', 'cfqth0fcgm'), ('refresh_token', 'QnIWrJDCPWSS9bevxSryDkizUVClej')]), EnvironHeaders([('X-Forwarded-For', '223.181.8.130, 223.181.8.130'), ('X-Forwarded-Proto', 'https'), ('X-Frappe-Site-Name', 'stergystaging.frappe.cloud'), ('Host', 'www.stergycleantech.com'), ('X-Use-X-Accel-Redirect', 'True'), ('Connection', 'close'), ('Content-Length', '90'), ('X-Real-Ip', '223.181.8.130'), ('Accept', 'application/json, text/javascript; q=0.01'), ('Content-Type', 'application/x-www-form-urlencoded'), ('Accept-Encoding', 'gzip, deflate, br'), ('User-Agent', 'Raven/55 CFNetwork/3860.300.31 Darwin/25.2.0'), ('Accept-Language', 'en-GB,en;q=0.9'), ('Priority', 'u=3, i'), ('Cookie', 'sid=Guest')]), None)
      kwargs = {}
      f = <function TokenEndpoint.create_token_response at 0x7f255cb68180>
  File "env/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/endpoints/token.py", line 114, in create_token_response
    return grant_type_handler.create_token_response(
      self = <oauthlib.openid.connect.core.endpoints.pre_configured.Server object at 0x7f2557596150>
      uri = 'https://www.stergycleantech.com/api/method/frappe.integrations.oauth2.get_token'
      http_method = 'POST'
      body = ImmutableMultiDict([('grant_type', 'refresh_token'), ('client_id', 'cfqth0fcgm'), ('refresh_token', 'QnIWrJDCPWSS9bevxSryDkizUVClej')])
      headers = EnvironHeaders([('X-Forwarded-For', '223.181.8.130, 223.181.8.130'), ('X-Forwarded-Proto', 'https'), ('X-Frappe-Site-Name', 'stergystaging.frappe.cloud'), ('Host', 'www.stergycleantech.com'), ('X-Use-X-Accel-Redirect', 'True'), ('Connection', 'close'), ('Content-Length', '90'), ('X-Real-Ip', '223.181.8.130'), ('Accept', 'application/json, text/javascript; q=0.01'), ('Content-Type', 'application/x-www-form-urlencoded'), ('Accept-Encoding', 'gzip, deflate, br'), ('User-Agent', 'Raven/55 CFNetwork/3860.300.31 Darwin/25.2.0'), ('Accept-Language', 'en-GB,en;q=0.9'), ('Priority', 'u=3, i'), ('Cookie', 'sid=Guest')])
      credentials = None
      grant_type_for_scope = None
      claims = None
      request = <oauthlib.Request SANITIZED>
      grant_type_handler = <oauthlib.openid.connect.core.grant_types.refresh_token.RefreshTokenGrant object at 0x7f2557597e10>
  File "env/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/grant_types/refresh_token.py", line 66, in create_token_response
    token = modifier(token, token_handler, request)
      self = <oauthlib.oauth2.rfc6749.grant_types.refresh_token.RefreshTokenGrant object at 0x7f2557596290>
      request = <oauthlib.Request SANITIZED>
      token_handler = ********
      headers = {'Content-Type': 'application/json', 'Cache-Control': 'no-store', 'Pragma': 'no-cache'}
      token = ********
      modifier = <bound method RefreshTokenGrant.add_id_token of <oauthlib.openid.connect.core.grant_types.refresh_token.RefreshTokenGrant object at 0x7f2557597e10>>
  File "env/lib/python3.11/site-packages/oauthlib/openid/connect/core/grant_types/refresh_token.py", line 34, in add_id_token
    return super().add_id_token(token, token_handler, request)
      self = <oauthlib.openid.connect.core.grant_types.refresh_token.RefreshTokenGrant object at 0x7f2557597e10>
      token = ********
      token_handler = ********
      request = <oauthlib.Request SANITIZED>
      __class__ = <class 'oauthlib.openid.connect.core.grant_types.refresh_token.RefreshTokenGrant'>
  File "env/lib/python3.11/site-packages/oauthlib/openid/connect/core/grant_types/base.py", line 142, in add_id_token
    token['id_token'] = self.request_validator.finalize_id_token(id_token, token, token_handler, request)
      self = <oauthlib.openid.connect.core.grant_types.refresh_token.RefreshTokenGrant object at 0x7f2557597e10>
      token = ********
      token_handler = ********
      request = <oauthlib.Request SANITIZED>
      nonce = None
      id_token = ********
  File "apps/frappe/frappe/oauth.py", line 317, in finalize_id_token
    userinfo = get_userinfo(user)
      self = <frappe.oauth.OAuthWebRequestValidator object at 0x7f2557595190>
      id_token = ********
      token = ********
      token_handler = ********
      request = <oauthlib.Request SANITIZED>
      id_token_header = ********
      user = <User: unsaved>
  File "apps/frappe/frappe/oauth.py", line 549, in get_userinfo
    if user.user_image:
      user = <User: unsaved>
      picture = None
      frappe_server_url = 'https://www.stergycleantech.com'
      valid_url_schemes = ('http', 'https', 'ftp', 'ftps')
builtins.AttributeError: 'User' object has no attribute 'user_image'

**Comment by nikkothari22** [comment]
Yep, I was able to reproduce this as well - happened on my own site 😅

Will take a look. Luckily this looks like an issue with the backend and not the mobile app.

**Comment by nikkothari22** [comment]
I don't see any error log on my site though - weird. I logged out and logged in again and it's working now - but maybe it throws the error again after an hour? So difficult to debug this. Checked Frappe's codebase and no changes have been made to oauth2 in a while. 

@jpettan Did you update both Raven and Frappe to the latest versions today? Or just Raven?

**Comment by jpettan** [comment]
Both apps updated today to the latest version.

**Comment by jpettan** [comment]
Yes, you get logged out. You can login again, but after an hour you are logged out again.

**Comment by jpettan** [comment]
I copy-pasted the error into perplexity and it gave me following lecture -

**The error occurs during an OAuth2 refresh token request in Frappe Framework (likely ERPNext), where an unsaved User object lacks the 'user_image' attribute expected by frappe.oauth.get_userinfo.**[1]

This happens because the OAuth flow creates a temporary `<User: unsaved>` instance (without loading from DB via `frappe.get_doc`), so standard DocType fields like `user_image` (an Attach Image field in the User doctype) aren't available until `user.load()` or `user.reload()` is called.[1]

## Root Cause
In `frappe/oauth.py` line 549, `get_userinfo(user)` directly accesses `user.user_image` without ensuring the User doc is fully loaded from the database.  The refresh token handler in `oauthlib` passes this incomplete user object during ID token finalization.[2][3]

## Quick Fix
Run these in the **Bench Console** (`bench --site [site_name] console`) on your Stergy Cleantech staging site to reload the specific user and test:

```
import frappe
user_email = "the_affected_user@example.com"  # Replace with the user email from the token
user = frappe.get_doc("User", user_email)
user.reload()  # Ensures all fields like user_image are loaded
print(hasattr(user, 'user_image'))  # Should print True
```

If the user lacks a `user_image`, explicitly set it (e.g., to empty or a default):
```
user.user_image = ""  # or a valid image path
user.save()
```

## Permanent Solutions
### Option 1: Patch oauth.py (Immediate)
Edit `apps/frappe/frappe/oauth.py` around line 549 in `get_userinfo`:
```python
def get_userinfo(user):
    if user.docstatus is None:  # or check if hasattr(user, 'name') and not user.name
        user = frappe.get_doc("User", user.name)
    picture = user.user_image or ""
    # rest of function...
```
Bench migrate after changes: `bench migrate`.[1]

### Option 2: Update Frappe/ERPNext
Check your version (`bench --site [site]` version). Update to latest develop or v15+: `bench update`. Recent versions handle User loading better in OAuth flows.[4]

### Option 3: Client-Side Workaround
In your Raven app (from User-Agent), regenerate tokens by re-authorizing the OAuth flow instead of relying on refresh tokens until fixed. Revoke invalid refresh tokens in Frappe's OAuth Client doctype.[5]

Test the endpoint post-fix: POST to `/api/method/frappe.integrations.oauth2.get_token` with your params. Monitor Frappe error logs (`bench --site [site] logs --app frappe`).[6]

Sources
[1] frappe/frappe/core/doctype/user/user.py at develop · frappe/frappe https://github.com/frappe/frappe/blob/develop/frappe/core/doctype/user/user.py
[2] AttributeError: 'User' object has no attribute 'frappe_userid' https://discuss.frappe.io/t/attributeerror-user-object-has-no-attribute-frappe-userid/17719
[3] Form Image Field: All About DocType Form in Frappe Framework https://www.youtube.com/watch?v=a3he-BVesUU
[4] OAuth2 - Documentation for Frappe Apps https://docs.frappe.io/framework/oauth2
[5] Fix OAuth Refresh Token Issues in n8n - Toolient https://www.toolient.com/2025/12/fix-oauth-refresh-token-issues-n8n.html
[6] Problem setting up OAuth in Frappe https://discuss.frappe.io/t/problem-setting-up-oauth-in-frappe/29073
[7] Getting a 'AttributeError at /login/authenticated', 'User' ... https://stackoverflow.com/questions/6192747/getting-a-attributeerror-at-login-authenticated-user-object-has-no-attribu
[8] AttributeError at /o/token/: 'User' object has no attribute 'id' https://github.com/django-oauth/django-oauth-toolkit/issues/1329
[9] AttributeError: 'NoneType' object has no attribute 'get' ... https://github.com/frappe/erpnext/issues/38707
[10] 'User' object has no attribute 'image' https://stackoverflow.com/questions/51512004/user-object-has-no-attribute-image
[11] frappe/frappe/utils/oauth.py at develop · frappe/frappe https://github.com/frappe/frappe/blob/develop/frappe/utils/oauth.py
[12] OAuth access and refresh tokens are missing from my request ... https://learn.microsoft.com/en-us/answers/questions/1294129/oauth-access-and-refresh-tokens-are-missing-from-m
[13] Request object has no attribute 'oauth2_error' in DRF + DOT https://stackoverflow.com/questions/56614021/request-object-has-no-attribute-oauth2-error-in-drf-dot
[14] OAuth Userinfo Endpoint https://discuss.frappe.io/t/oauth-userinfo-endpoint/83352
[15] Id_token and refresh_token are missing in the /oauth/token ... https://community.auth0.com/t/id-token-and-refresh-token-are-missing-in-the-oauth-token-response/30401
[16] OAuth profile error https://discuss.frappe.io/t/oauth-profile-error/65031
[17] AttributeError: 'User' object has no attribute 'backend' https://www.reddit.com/r/djangolearning/comments/ey35do/attributeerror_user_object_has_no_attribute/
[18] frappe/frappe/integrations/oauth2.py at develop https://github.com/frappe/frappe/blob/develop/frappe/integrations/oauth2.py
[19] Field Types - Documentation for Frappe Apps https://docs.frappe.io/framework/user/en/basics/doctypes/fieldtypes
[20] Use user image in another doctype - Frappe Forum https://discuss.frappe.io/t/use-user-image-in-another-doctype/9087
[21] Add multiple images on Frappe DocType field https://stackoverflow.com/questions/72947776/add-multiple-images-on-frappe-doctype-field
[22] Customization : DocType | Frappe Content licensed CC-BY ... https://help.onehash.ai/en/article/customization-doctype-u3f5w5/
[23] User image Error - ERPNext https://discuss.frappe.io/t/user-image-error/34779
[24] OAuth 2 - Documentation for Frappe Apps https://docs.frappe.io/framework/user/en/guides/integration/rest_api/oauth-2
[25] Frappe, ERPNext Doctype Generator https://gist.github.com/esafwan/cc823f944bbe9f76a50a8e0200729a4e
[26] AttributeError: 'ERPNextAddress' object has no attribute ' ... https://github.com/frappe/erpnext/issues/35698
[27] Using Frappe as OAuth Service https://docs.frappe.io/framework/user/en/using_frappe_as_oauth_service
[28] Create a DocType https://frappeframework.com/docs/v15/user/en/tutorial/create-a-doctype

**Comment by nikkothari22** [comment]
@jpettan Yeah AI is just not helpful here. I am able to reproduce this now - I just expire my oauth tokens and allow it to refresh - and that fails. Looking into it. Seems like an issue with framework though.

**Comment by nikkothari22** [comment]
I can also reproduce this on v16 and develop. Might be related to the `oauthlib` version upgrade here: https://github.com/frappe/frappe/pull/36509

Edit: nope, the way I was reproducing it was by force expiring OAuth Bearer tokens - whereas the client (mobile app) thought that the token is still valid for another 40-50 minutes.

Edit edit: Yep, it was related to that.

**Comment by nikkothari22** [comment]
Nope, not related to that. This is just going in circles now. @jpettan Does the error go away when you close and reopen the app?

Ideally, if a token is about to expire, the app should try refreshing the token - which is working for me. The error log you're seeing is related to the user_image column - and I'm not seeing the same error :/

**Comment by nikkothari22** [comment]
@jpettan So I figured it out - this was happening because the refresh token API call was not working on Frappe v15 after oauthlib was updated. The PR linked above will fix this issue in the framework. For the time being, you can manually logout and login till that PR is merged.

**Comment by jpettan** [comment]
Resolved with frappe framework v15.100.0
